export const LAST_UPDATED = "2026-02-26";

export const EMPLOYMENT_ADJUSTMENTS = {
  government: {
    label: "Govt Employee",
    rateDelta: -0.001,
  },
  private: {
    label: "Private Company Employee",
    rateDelta: 0.001,
  },
};

export const productPricingConfig = {
  "payday-emergency-loan": {
    minAmount: 30000,
    maxAmount: 1000000,
    allowedTerms: [1],
    rateType: "fee_only",
    baseMonthlyRate: 0,
    processingFeeRate: 0.08,
    repaymentStyle: "Single-cycle short repayment (7–30 days)",
    assumptions: "No monthly interest. A flat servicing/processing fee applies.",
  },
  "individual-business-loan": {
    minAmount: 1000000,
    maxAmount: 10000000,
    allowedTerms: [6, 9, 12],
    rateType: "reducing",
    baseMonthlyRate: 0.05,
    processingFeeRate: 0.02,
    repaymentStyle: "Monthly installment over fixed term",
    assumptions: "Declining balance model with profile-based rate band.",
  },
  "rain-fed-dzinja-seasonal-loan": {
    minAmount: 150000,
    maxAmount: 1000000,
    allowedTerms: [7, 8, 9],
    rateType: "flat",
    baseMonthlyRate: 0.058,
    processingFeeRate: 0.015,
    repaymentStyle: "Seasonal bullet repayment aligned to harvest",
    assumptions: "Seasonal structure may defer early repayment burden.",
  },
  "irrigation-mthilira-loan": {
    minAmount: 100000,
    maxAmount: 5000000,
    allowedTerms: [4, 5, 6],
    rateType: "reducing",
    baseMonthlyRate: 0.05,
    processingFeeRate: 0.015,
    repaymentStyle: "Short-cycle repayment for dry-season crops",
    assumptions: "Designed for fast-yield crop cycles.",
  },
  "agricultural-asset-financing": {
    minAmount: 500000,
    maxAmount: 75000000,
    allowedTerms: [12, 18, 24, 30, 36],
    rateType: "reducing",
    baseMonthlyRate: 0.04,
    processingFeeRate: 0.015,
    repaymentStyle: "Medium-term installment, asset-backed",
    assumptions: "Asset quality and collateral coverage affect final pricing.",
  },
  "education-school-fees-loan": {
    minAmount: 50000,
    maxAmount: 3000000,
    allowedTerms: [3, 6, 9, 10],
    rateType: "flat",
    baseMonthlyRate: 0.055,
    processingFeeRate: 0.015,
    repaymentStyle: "Short-term tuition-linked repayment",
    assumptions: "Invoice-based education financing.",
  },
  "revolving-term-loan": {
    minAmount: 100000,
    maxAmount: 5000000,
    allowedTerms: [6, 12, 18],
    rateType: "reducing",
    baseMonthlyRate: 0.048,
    processingFeeRate: 0.012,
    repaymentStyle: "Top-up / redraw facility for repeat clients",
    assumptions: "Available to qualified repeat borrowers only.",
  },
  "payroll-deduction-loan": {
    minAmount: 200000,
    maxAmount: 10000000,
    allowedTerms: [12, 24, 36, 48, 60],
    rateType: "reducing",
    baseMonthlyRate: 0.035,
    processingFeeRate: 0.01,
    repaymentStyle: "Salary deduction over long tenor",
    assumptions: "Employer deduction mechanism lowers risk profile.",
  },
  "solidarity-group-loan": {
    minAmount: 20000,
    maxAmount: 500000,
    allowedTerms: [4, 5, 6],
    rateType: "flat",
    baseMonthlyRate: 0.06,
    processingFeeRate: 0.01,
    repaymentStyle: "Weekly / bi-weekly group repayments",
    assumptions: "Solidarity model shares repayment responsibility.",
  },
  "micro-health-emergency-loan": {
    minAmount: 50000,
    maxAmount: 2000000,
    allowedTerms: [3, 6, 9, 12],
    rateType: "flat",
    baseMonthlyRate: 0.055,
    processingFeeRate: 0.012,
    repaymentStyle: "Emergency use with bundled protection",
    assumptions: "Medical emergency and protection-linked product behavior.",
  },
};
